### ISSUE TITLE
Noticeable delay with application of custom CSS

### ISSUE THREAD

**Issue by KarolS** [Kagu-chan/anki-jpdb.reader#235]
The custom CSS is applied with noticeable delay. Sometimes it's a tiny fraction of a second, sometimes is even longer, up to 10 seconds or so.

The problem applies to both the popup window and newly parsed text. 
This is especially noticeble if you use color:inherit, so a temporary lack of custom CSS flashes green text.
It's especially annoying on websites that are parsed automatically, like Wikipedia and Youtube, but also Ttsu.

My word CSS:
```css
.jpdb-word.not-in-deck { color: rgb(222, 111, 222); }
.jpdb-word.known:not(div.vocabulary-list .jpdb-word.known):not(div.jp .jpdb-word.known) { color: inherit; }
.jpdb-word.never-forget:not(div.vocabulary-list .jpdb-word.never-forget):not(div.jp .jpdb-word.never-forget) { color: inherit; }
.jpdb-word.suspended:not(div.vocabulary-list .jpdb-word.suspended):not(div.jp .jpdb-word.suspended) { color: inherit; }
.jpdb-word.blacklisted:not(div.vocabulary-list .jpdb-word.blacklisted):not(div.jp .jpdb-word.blacklisted) { color: inherit; }
.jpdb-word.locked:not(div.vocabulary-list .jpdb-word.locked):not(div.jp .jpdb-word.locked):not(.jpdb-word.new):not(.jpdb-word.not-in-deck):not(.jpdb-word.due):not(.jpdb-word.failed) { color: inherit; }
.jpdb-word.unparsed { color: inherit; }
.jpdb-word.misparsed{ color: inherit; background:inherit;}
```

My popup CSS:
```css

.popup {
max-height:600px !important;
font-family: Lato;
border: 1px solid grey;
}
section#details {
}
div#header>a#link {
font-family: "Yu Mincho";
font-size:24pt !important;
border-bottom:none !important;
color:#dddddd;
}
section#mining>a, section#grading > a {
box-shadow: none !important;
font-size:10pt!important;
}

```

Video of the glitch happening: 
https://streamable.com/f13odw or [2025-05-16 19-02-22.zip](https://github.com/user-attachments/files/20257159/2025-05-16.19-02-22.zip)
